### ISSUE TITLE
Crash on selling item to Market Gooey

### ISSUE THREAD

**Issue by jdrueckert** [Terasology/MetalRenegades#167]
Playing MetalRenegades in Singleplayer. Tried to sell an item I found in an earlier session to the market gooey of a city I also found in that earlier session. Game crashed when hitting the "Sell" button.

```
21:57:58.944 [main] ERROR o.t.engine.core.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
        at org.terasology.metalrenegades.economy.systems.MarketManagementSystem.sell(MarketManagementSystem.java:195)
        at org.terasology.metalrenegades.economy.systems.MarketManagementSystem.onMarketTransactionRequest(MarketManagementSystem.java:160)
        at org.terasology.metalrenegades.economy.systems.MarketManagementSystemMethodAccess.invoke(Unknown Source)
        at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:379)
        at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.sendStandardEvent(EventSystemImpl.java:244)
        at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:235)
        at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
        at org.terasology.engine.network.NetworkEventSystemDecorator.send(NetworkEventSystemDecorator.java:54)
        at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
        at org.terasology.engine.recording.RecordingEventSystemDecorator.send(RecordingEventSystemDecorator.java:34)
        at org.terasology.engine.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:190)
        at org.terasology.metalrenegades.economy.ui.MarketScreen.lambda$initialise$1(MarketScreen.java:128)
        at org.terasology.nui.ActivatableWidget.activateWidget(ActivatableWidget.java:46)
        at org.terasology.nui.widgets.UIButton.activateWidget(UIButton.java:203)
        at org.terasology.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:94)
        at org.terasology.nui.canvas.CanvasImpl.processMouseRelease(CanvasImpl.java:266)
        at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:680)
        at org.terasology.engine.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
        at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:379)
        at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:254)
        at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:233)
        at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
        at org.terasology.engine.network.NetworkEventSystemDecorator.send(NetworkEventSystemDecorator.java:54)
        at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
        at org.terasology.engine.recording.RecordingEventSystemDecorator.send(RecordingEventSystemDecorator.java:34)
        at org.terasology.engine.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:190)
        at org.terasology.engine.input.InputSystem.send(InputSystem.java:524)
        at org.terasology.engine.input.InputSystem.sendMouseEvent(InputSystem.java:496)
        at org.terasology.engine.input.InputSystem.processMouseButtonInput(InputSystem.java:216)
        at org.terasology.engine.input.InputSystem.processMouseInput(InputSystem.java:195)
        at org.terasology.engine.input.InputSystem.update(InputSystem.java:130)
        at org.terasology.engine.core.modes.StateIngame.handleInput(StateIngame.java:200)
        at org.terasology.engine.core.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:39)
        at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:509)
        at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:460)
        at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:436)
        at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:402)
        at org.terasology.engine.Terasology.call(Terasology.java:207)
        at org.terasology.engine.Terasology.call(Terasology.java:70)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at org.terasology.engine.Terasology.main(Terasology.java:139)
```

**Comment by jdrueckert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Playtest Findings](https://trello.com/c/X0iLPJA4/168-fix-playtest-findings)
