### ISSUE TITLE
Crash on adding `DynamicWorld` generator in AGS for Metal Renegades

### ISSUE THREAD

**Issue by jdrueckert** [Terasology/MetalRenegades#172]
Terasology crashed when I tried to add the `DynamicWorld` generator in advanced game setup for Metal Renegades. It's coming from the `FloraFeatureGenerato` in `GrowingFlora`: https://github.com/Terasology/GrowingFlora/blob/develop/src/main/java/org/terasology/gf/generator/FloraFeatureGenerator.java#L58

I assume that before loading the game, `WorldGeneratorPluginLibrary` is not yet registered in the `CoreRegistry` which is why `CoreRegistry.get(WorldGeneratorPluginLibrary.class)` returns `null`.

Stacktrace:
```
java.lang.NullPointerException: null
	at org.terasology.gf.generator.FloraFeatureGenerator.loadPlantGrowthDefinitions(FloraFeatureGenerator.java:58)
	at org.terasology.gf.generator.FloraFeatureGenerator.<init>(FloraFeatureGenerator.java:45)
	at org.terasology.metalrenegades.world.dynamic.DynamicWorldGenerator.createWorld(DynamicWorldGenerator.java:73)
	at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.getWorldBuilder(BaseFacetedWorldGenerator.java:94)
	at org.terasology.engine.world.generation.BaseFacetedWorldGenerator.getConfigurator(BaseFacetedWorldGenerator.java:74)
	at org.terasology.engine.rendering.nui.layers.mainMenu.WorldSetupScreen.configureProperties(WorldSetupScreen.java:162)
	at org.terasology.engine.rendering.nui.layers.mainMenu.WorldSetupScreen.setWorld(WorldSetupScreen.java:146)
	at org.terasology.engine.rendering.nui.layers.mainMenu.UniverseSetupScreen.lambda$initialise$1(UniverseSetupScreen.java:173)
	at org.terasology.nui.ActivatableWidget.activateWidget(ActivatableWidget.java:46)
	at org.terasology.nui.widgets.UIButton.activateWidget(UIButton.java:203)
	at org.terasology.nui.widgets.UIButton$1.onMouseRelease(UIButton.java:94)
	at org.terasology.nui.canvas.CanvasImpl.processMouseRelease(CanvasImpl.java:266)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternal.mouseButtonEvent(NUIManagerInternal.java:680)
	at org.terasology.engine.rendering.nui.internal.NUIManagerInternalMethodAccess.invoke(Unknown Source)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl$ByteCodeEventHandlerInfo.invoke(EventSystemImpl.java:379)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.sendConsumableEvent(EventSystemImpl.java:254)
	at org.terasology.engine.entitySystem.event.internal.EventSystemImpl.send(EventSystemImpl.java:233)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.network.NetworkEventSystemDecorator.send(NetworkEventSystemDecorator.java:54)
	at org.terasology.engine.core.bootstrap.eventSystem.AbstractEventSystemDecorator.send(AbstractEventSystemDecorator.java:67)
	at org.terasology.engine.recording.RecordingEventSystemDecorator.send(RecordingEventSystemDecorator.java:34)
	at org.terasology.engine.entitySystem.entity.internal.BaseEntityRef.send(BaseEntityRef.java:190)
	at org.terasology.engine.input.InputSystem.send(InputSystem.java:524)
	at org.terasology.engine.input.InputSystem.sendMouseEvent(InputSystem.java:496)
	at org.terasology.engine.input.InputSystem.processMouseButtonInput(InputSystem.java:216)
	at org.terasology.engine.input.InputSystem.processMouseInput(InputSystem.java:195)
	at org.terasology.engine.input.InputSystem.update(InputSystem.java:130)
	at org.terasology.engine.core.modes.StateMainMenu.handleInput(StateMainMenu.java:133)
	at org.terasology.engine.core.subsystem.lwjgl.LwjglInput.postUpdate(LwjglInput.java:39)
	at org.terasology.engine.core.TerasologyEngine.tick(TerasologyEngine.java:509)
	at org.terasology.engine.core.TerasologyEngine.mainLoop(TerasologyEngine.java:460)
	at org.terasology.engine.core.TerasologyEngine.runMain(TerasologyEngine.java:436)
	at org.terasology.engine.core.TerasologyEngine.run(TerasologyEngine.java:402)
	at org.terasology.engine.Terasology.call(Terasology.java:207)
	at org.terasology.engine.Terasology.call(Terasology.java:70)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
	at picocli.CommandLine.access$1200(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at org.terasology.engine.Terasology.main(Terasology.java:139)
```

**Comment by jdrueckert** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [MetalRenegades AGS crash](https://trello.com/c/23Whlokf/172-metalrenegades-ags-crash)

**Comment by jdrueckert** [comment]
Fixed by https://github.com/Terasology/GrowingFlora/pull/42
